<h1 style="color:#0d3b66;">CELIAC-SAFE RESTAURANT FINDER</h1>

- Defining the problem statement  
- Collecting and cleaning restaurant reviews  
- Text preprocessing and feature engineering  
- Model training and evaluation  
- Building an interactive gluten-free restaurant map

## <span style="color:#2F5D9F">1) Defining the problem statement</span>

In this project, we aim to identify restaurants that are potentially safe for people with celiac disease using real customer reviews.

We collect and analyze textual data from restaurant reviews in Melbourne and Sydney, focusing on signals related to gluten-free safety, cross-contamination, and user experiences.

The goal is to build a classification model that can detect whether a restaurant appears to be safe based on these reviews, and use this information to create an interactive map that helps users find gluten-free friendly places more easily.

## <span style="color:#2F5D9F">2) Collecting the data</span>

The dataset consists of publicly available restaurant reviews collected and preprocessed for this project.

Import the required Python libraries

In [1]:
import re
import unicodedata
import pandas as pd
from rapidfuzz import fuzz

Reading the dataset using Pandas

In [3]:
df = pd.read_csv("data/raw_data.csv")
df.head(5)

,isLocalGuide,likesCount,name,originalLanguage,publishAt,publishedAtDate,rating,responseFromOwnerDate,responseFromOwnerText,reviewId,...,text,textTranslated,translatedLanguage,visitedIn,title,address,placeId,categoryName,price,menu
0,True,0,NaN,en,2 days ago,2026-03-28T09:42:24.780Z,NaN,2026-03-28T11:52:51.000Z,Thanks for your review Jiawen! 🙇🏻‍♀️❤️,Ci9DQUlRQUNvZENodHljRjlvT21KVVZ6TmhhM0J0VTBWaW...,...,Bagels were really tasty though quite messy to...,NaN,NaN,NaN,Schmucks Bagels,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",ChIJLaFu24xd1moRM5S_cRJ2Ehg,Bagel shop,A$1–20,NaN
1,True,0,NaN,NaN,5 days ago,2026-03-25T21:35:38.191Z,NaN,2026-03-28T11:53:26.000Z,Thank you so much Andreas ❤️🙇🏻‍♀️,Ci9DQUlRQUNvZENodHljRjlvT2xSbFZXczRiV0pSYjNsNm...,...,NaN,NaN,NaN,NaN,Schmucks Bagels,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",ChIJLaFu24xd1moRM5S_cRJ2Ehg,Bagel shop,A$1–20,NaN
2,False,0,NaN,en,Edited 5 days ago,2026-03-25T08:44:10.850Z,NaN,NaN,NaN,Ci9DQUlRQUNvZENodHljRjlvT25wclJWOVdWamRQU0ZOUG...,...,Excellent food and service …also do gluten fre...,NaN,NaN,NaN,Schmucks Bagels,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",ChIJLaFu24xd1moRM5S_cRJ2Ehg,Bagel shop,A$1–20,NaN
3,False,0,NaN,en,5 days ago,2026-03-25T04:04:01.450Z,NaN,2026-03-25T09:01:43.000Z,Thank you lovely!! We are really appreciated y...,Ci9DQUlRQUNvZENodHljRjlvT2s1ZllVYzVaRTl5VUZoVF...,...,Really nice place with tasty bagels! We‘ve bee...,NaN,NaN,NaN,Schmucks Bagels,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",ChIJLaFu24xd1moRM5S_cRJ2Ehg,Bagel shop,A$1–20,NaN
4,True,0,NaN,NaN,6 days ago,2026-03-24T21:53:00.229Z,NaN,2026-03-25T03:24:22.000Z,Thank you Louise! 🙇🏻‍♀️❤️,Ci9DQUlRQUNvZENodHljRjlvT25WUlFYSm9SVTR6VG5SaG...,...,NaN,NaN,NaN,NaN,Schmucks Bagels,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",ChIJLaFu24xd1moRM5S_cRJ2Ehg,Bagel shop,A$1–20,NaN

## <span style="color:#2F5D9F">3) Data cleaning</span>

In this stage, the dataset is cleaned and standardized to make the reviews consistent and suitable for analysis and model training.

The main steps include text unification, column selection, missing value handling, and text normalization.

### 3.1 Text unification
Use translated text if available, otherwise original

In [4]:
df["raw_review_text"] = (
    df["textTranslated"]
    .replace("", pd.NA)
    .combine_first(df["text"])
)

### 3.2 Column cleaning and selection
Cleaning and selecting key columns.

In [5]:
cols = [
    "title","raw_review_text", "address", "categoryName", "price", "menu", "placeId"
]
for col in cols:
    if col in df.columns:
        df[col] = df[col].fillna("").astype(str).str.strip()

df = df[cols].copy()

### 3.3 Text normalization
Standardize text for matching and analysis

In [6]:
def normalize_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower().strip()

    # quitar acentos
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))

    # normalizar separadores
    text = re.sub(r"[-_/]", " ", text)

    # quitar ruido
    text = re.sub(r"[^\w\s]", " ", text)

    # espacios
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_review_text"] = df["raw_review_text"].apply(normalize_text)

### 3.4 Remove invalid rows

Drop rows with missing placeId or empty reviews.

In [7]:
df = df[
    (df["placeId"].notna()) &
    (df["placeId"] != "") &
    (df["clean_review_text"] != "")
].copy()

### 3.5 Remove duplicates

Keep unique reviews by placeId and normalized review text.

In [8]:
df = df.drop_duplicates(subset=["placeId", "clean_review_text"])

### 3.6 Save cleaned data

In [9]:
df.to_csv("data/dataclean_data.csv", index=False)
df.head(5)

,title,raw_review_text,address,categoryName,price,menu,placeId,clean_review_text
0,Schmucks Bagels,Bagels were really tasty though quite messy to...,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,bagels were really tasty though quite messy to...
2,Schmucks Bagels,Excellent food and service …also do gluten fre...,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,excellent food and service also do gluten free...
3,Schmucks Bagels,Really nice place with tasty bagels! We‘ve bee...,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,really nice place with tasty bagels we ve been...
8,Schmucks Bagels,Delicious,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,delicious
9,Schmucks Bagels,Delicious and very filling. The dishes were be...,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,delicious and very filling the dishes were bea...

## <span style="color:#2F5D9F">4) Text feature extraction</span>
Detect gluten-related mentions in reviews using regex patterns and fuzzy matching.

### 4.1 Pattern-based gluten mention detection

Pattern-based gluten mention detection

In [10]:
gluten_patterns = [
    r"\bgluten\b",
    r"\bgluten free\b",
    r"\bglutenfree\b",
    r"\bgf\b",
    r"\bceliac\b",
    r"\bcoeliac\b",
    r"\bceliac disease\b",
    r"\bgluten intolerance\b",
    r"\bcross contamination\b",
    r"\bcrosscontamination\b",
    r"\bno cross contamination\b",
    r"\bdedicated fryer\b",
    r"\bseparate fryer\b",
    r"\bdedicated kitchen\b",
    r"\bseparate kitchen\b",
    r"\bgluten safe\b",
    r"\bsafe for celiac\b",
    r"\bceliac friendly\b",
    r"\bgluten friendly\b",
    r"\bgf options\b",
    r"\bgf menu\b",
    r"\bgluten free options\b",
    r"\bgluten free menu\b",
]
combined_pattern = re.compile("|".join(gluten_patterns), flags=re.IGNORECASE)

### 4.2 Detecting gluten mentions in reviews

dentify whether a review contains gluten-related terms using regex and fuzzy matching, and store the matched keyword.

In [11]:
def gluten_match_info(text):
    if not isinstance(text, str) or not text.strip():
        return False, None

    m = combined_pattern.search(text)
    if m:
        return True, m.group(0)

    words = text.split()
    for w in words:
        if len(w) >= 5 and fuzz.ratio(w, "gluten") >= 85:
            return True, f"fuzzy:{w}"

    return False, None

match_result = df["clean_review_text"].apply(gluten_match_info)
df["gluten_match"] = match_result.apply(lambda x: x[0])
df["gluten_trigger"] = match_result.apply(lambda x: x[1])

## <span style="color:#2F5D9F">5) Safety classification</span>

This section classifies individual reviews based on sentiment and explicit gluten-related safety signals. The goal is to identify whether a review suggests that a restaurant is safe, unsafe, or lacks sufficient information for people with celiac disease

### 5.1 Helper function

This function checks whether a given text contains any of the specified regex patterns.

In [12]:
def has(text, patterns):
    return any(re.search(p, text) for p in patterns)

### 5.2 Sentiment definition

Lists of positive and negative keywords used to perform a simple rule-based sentiment analysis on review text.

In [13]:
positive_words = ["good","great","amazing","excellent","love","safe","delicious","friendly"]
negative_words = ["bad","terrible","awful","sick","unsafe","rude","horrible"]

### 5.3 Sentiment classificaction

This function assigns a sentiment label (positive or negative) to each review based on the presence of predefined keywords.

In [14]:
def get_sentiment(text):
    words = text.split()
    pos = sum(w in words for w in positive_words)
    neg = sum(w in words for w in negative_words)
    return "positive" if pos >= neg else "negative"

### 5.4 Safety/Unsafe pattern definition

Patterns that indicate a restaurant is likely safe or unsafe for gluten-free diets.

In [15]:
safety_patterns = [
    r"gluten[- ]?free",
    r"100 ?% gluten[- ]?free",
    r"separate fryer|dedicated fryer",
    r"dedicated kitchen|dedicated area",
    r"staff (knowledgeable|understood)",
    r"cross[- ]?contamination (aware|awareness|understood)",
    r"celiac safe|coeliac safe"
]
unsafe_patterns = [
        r"got sick",
        r"glutened",
        r"not safe",
        r"unsafe",
        r"cross[- ]?contamination"
    ]

### 5.5 Review safety classification

Classifies each review as safe, unsafe, or None based on detected patterns.

In [16]:
def classify_review(text):
    if not isinstance(text, str) or not text.strip():
        return pd.Series({"sentiment": None, "safety": None})

    text = normalize_text(text)

    sentiment = get_sentiment(text)

    if has(text, unsafe_patterns):
        safety = "unsafe"
    elif has(text, safety_patterns):
        safety = "safe"
    else:
        safety = None

    return pd.Series({
        "sentiment": sentiment,
        "safety": safety
    })

### 5.6 Applying classification to the dataset

In [17]:
df_reviews_classified = pd.concat(
    [
        df.reset_index(drop=True),
        df["clean_review_text"].apply(classify_review)
    ],
    axis=1
)

df_reviews_classified.head()

,title,raw_review_text,address,categoryName,price,menu,placeId,clean_review_text,gluten_match,gluten_trigger,sentiment,safety
0,Schmucks Bagels,Bagels were really tasty though quite messy to...,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,bagels were really tasty though quite messy to...,False,None,positive,None
1,Schmucks Bagels,Excellent food and service …also do gluten fre...,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,excellent food and service also do gluten free...,True,gluten,NaN,NaN
2,Schmucks Bagels,Really nice place with tasty bagels! We‘ve bee...,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,really nice place with tasty bagels we ve been...,False,None,positive,safe
3,Schmucks Bagels,Delicious,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,delicious,False,None,positive,None
4,Schmucks Bagels,Delicious and very filling. The dishes were be...,"Tenancy 9/567 Collins St, Melbourne VIC 3000, ...",Bagel shop,A$1–20,,ChIJLaFu24xd1moRM5S_cRJ2Ehg,delicious and very filling the dishes were bea...,False,None,NaN,NaN

## <span style="color:#2F5D9F">6) Restaurant safety ranking</span>

This section aggregates review-level classifications to evaluate each restaurant and build a final safety ranking.

### 6.1 Aggregating reviews by restaurant

Aggregating reviews by restaurant

In [18]:
restaurant_ranking = (
    df_reviews_classified
    .groupby("title", as_index=False)
    .agg(
        total_reviews=("clean_review_text", "count"),
        safe_reviews=("safety", lambda x: (x == "safe").sum()),
        unsafe_reviews=("safety", lambda x: (x == "unsafe").sum())
    )
)

### 6.2 Computing classified reviews and safety percentage

Calculates how many reviews were classified and the percentage of safe reviews.

In [19]:
restaurant_ranking["classified_reviews"] = (
    restaurant_ranking["safe_reviews"] + restaurant_ranking["unsafe_reviews"]
)

restaurant_ranking["safety_pct"] = (
    restaurant_ranking["safe_reviews"] / restaurant_ranking["classified_reviews"]
).fillna(0)

### 6.3 Computing the ranking score

Creates a weighted score prioritizing safe reviews, penalizing unsafe ones, and considering review volume.

In [20]:
restaurant_ranking["ranking_score"] = (
    restaurant_ranking["safe_reviews"] * 2
    - restaurant_ranking["unsafe_reviews"] * 3
    + restaurant_ranking["classified_reviews"] * 0.5
)

### 6.4 Assigning safety labels

Classifies restaurants based on the percentage of safe reviews.

In [21]:
restaurant_ranking["safety_label"] = pd.cut(
    restaurant_ranking["safety_pct"],
    bins=[-1, 0.5, 0.7, 1],
    labels=["unsafe", "partly safe", "safe"]
)

### 6.5 Adding restaurant metadata

Extracts unique restaurant information and prepares it for merging.

In [22]:
restaurant_info = (
    df[
        ["title", "address", "placeId", "price", "categoryName", "menu"]
    ]
    .drop_duplicates(subset="title")
)

### 6.6 Merging ranking with restaurant information

Combines ranking metrics with restaurant details.

In [23]:
restaurant_ranking = restaurant_ranking.merge(
    restaurant_info,
    on="title",
    how="left"
)

### 6.7 Sorting the final ranking

Sorts restaurants by ranking score and number of safe reviews.

In [24]:
restaurant_ranking = restaurant_ranking.sort_values(
    by=["ranking_score", "safe_reviews"],
    ascending=False
).reset_index(drop=True)

restaurant_ranking.head()

,title,total_reviews,safe_reviews,unsafe_reviews,classified_reviews,safety_pct,ranking_score,safety_label,address,placeId,price,categoryName,menu
0,Piccolina Gelateria,718,120,1,121,0.991736,297.5,safe,"43 Hardware Ln, Melbourne VIC 3000, Australia",ChIJV5RpXR1d1moRVqlvLPQvIuk,$$,Ice cream shop,https://www.piccolinagelateria.com.au/shop
1,Roccella Italian Restaurant East Melbourne,846,107,4,111,0.963964,257.5,safe,"158 Clarendon St, East Melbourne VIC 3002, Aus...",ChIJiWZcQlZD1moReLf1KVvQ98M,A$40–60,Italian restaurant,https://www.roccellamelbourne.com.au/menu?utm_...
2,Regretless - Low Carb Pleasure,777,77,2,79,0.974684,187.5,safe,"Mid City Centre, Shop 13-14/200 Bourke St, Mel...",ChIJr_-E1mVD1moRXASlIAsvPtA,A$1–20,Cafe,https://regretlessau.square.site/cafe-menu
3,Roule Galette,738,49,0,49,1.000000,122.5,safe,"Shop 1/241 Flinders Ln, Melbourne VIC 3000, Au...",ChIJCYzQJbRC1moRnD9tQLJY4PU,A$20–40,French restaurant,http://www.roulegalette.com.au/crepe-and-galet...
4,Romo Pizza Bar,537,45,3,48,0.937500,105.0,safe,"21 Katherine Pl, Melbourne VIC 3000, Australia",ChIJxbr0FZFd1moRQHxEjpKLZIs,A$20–40,Pizza restaurant,http://www.romopizzabar.com.au/

## <span style="color:#2F5D9F">7) Adding geolocation data</span>

This section retrieves the geographic coordinates (latitude and longitude) for each restaurant using the Google Places API. These coordinates enable spatial analysis and map-based visualization.

In [25]:
import requests

API_KEY = "AIzaSyBIKmegmNXymxhxCLmtKqinf4Q36W0mMiU"

def get_lat_lng(place_id):
    url = "https://maps.googleapis.com/maps/api/place/details/json"
    params = {
        "place_id": place_id,
        "fields": "geometry",
        "key": API_KEY
    }
    r = requests.get(url, params=params).json()
    
    try:
        loc = r["result"]["geometry"]["location"]
        return loc["lat"], loc["lng"]
    except:
        return None, None

restaurant_ranking[["lat", "lng"]] = restaurant_ranking["placeId"].apply(lambda x: pd.Series(get_lat_lng(x)))

## <span style="color:#2F5D9F"> 8) Exporting final dataset</span>

This step saves the final restaurant ranking dataset, including safety scores and geolocation data, as a CSV file for further analysis or visualization.

In [26]:
restaurant_ranking.to_csv(
    "/Users/luciaterres/Desktop/data/restaurant_ranking.csv",
    index=False
)

OSError: Cannot save file into a non-existent directory: '/Users/luciaterres/Desktop/data'